# Generated by Django 5.2.1 on 2025-05-11 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('address', models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], max_length=10)),
                ('hearing_loss', models.CharField(choices=[('Severe', 'Severe'), ('Moderate', 'Moderate'), ('Mild', 'Mild')], max_length=10)),
                ('school_support', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('paid_classes', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('ia1', models.FloatField()),
                ('ia2', models.FloatField()),
                ('ia3', models.FloatField()),
                ('nursery_attendance', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('internet_access', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('study_time', models.CharField(choices=[('<1hr', '<1hr'), ('1-2hr', '1-2hr'), ('2-5hr', '2-5hr'), ('>5hr', '>5hr')], max_length=10)),
                ('extracurricular', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('absences', models.IntegerField()),
                ('predicted_marks', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
