# Generated by Django 5.2.1 on 2025-05-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
