# Generated by Django 5.2.1 on 2025-05-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teacher_email_teacher_reset_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='reset_token_created_at',
        ),
    ]
